<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "px_dbsequencer"
 *
 * Auto generated by Extension Builder 2014-03-07
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Database Sequencer',
    'description' => 'With this extension you can ensure different unique keys for the configured tables (e.g.: pages, pages_language_overlay, tt_content)',
    'category' => 'be',
    'author' => 'Andre Wuttig, Axel Boeswetter, Thomas Griessbach',
    'author_email' => 'wuttig@portrino.de, boeswetter@portrino.de, griessbach@portrino.de',
    'author_company' => 'portrino GmbH',
    'shy' => '',
    'priority' => '',
    'module' => '',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'modify_tables' => '',
    'clearCacheOnLoad' => 0,
    'lockType' => '',
    'version' => '0.11.0',
    'constraints' => [
        'depends' => [
			'typo3' => '11.5.0-11.5.99',
        ],
        'conflicts' => [
        ],
        'suggests' => [
        ],
    ],
];
