<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "px_dbsequencer"
 *
 * Auto generated by Extension Builder 2014-03-07
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Database Sequencer',
    'description' => 'With this extension you can ensure different unique keys for the configured tables (e.g.: pages, tt_content, ...)',
    'category' => 'be',
    'author' => 'Andre Wuttig, Axel Böswetter, Thomas Grießbach',
    'author_email' => 'dev@portrino.de',
    'author_company' => 'portrino GmbH',
    'state' => 'beta',
    'version' => '13.1.3',
    'constraints' => [
        'depends' => [
            'typo3' => '13.4.10-13.4.99',
        ],
        'conflicts' => [
        ],
        'suggests' => [
        ],
    ],
];
